force-app/main/default/objects/Matter__c/Matter__c.object-meta.xml
<CustomObject>
    <label>Matter</label>
    <nameField>
        <label>Matter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Matter__c/fields/Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>Decision_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Decision Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Matter_Number__c.field-meta.xml
<CustomField>
    <fullName>Matter_Number__c</fullName>
    <displayFormat>MM-{00000}</displayFormat>
    <label>Matter Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Awaiting Full Payment</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment - Overdue/Dunning Letter(s) Sent</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment - Referred to Treasury (should be able to add referred date)</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment - Referred to DOJ/US Attorney (should be able to add referred date)</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Penalty Paid in Full - Awaiting Completion of SEP/Compliance Order/Injunctive Relief</fullName>
            </value>
            <value>
                <fullName>No Penalty - Awaiting Completion of SEP/Compliance Order/Injunctive Relief</fullName>
            </value>
            <value>
                <fullName>Stayed - On Hold (proceedings paused pending interlocutory action)</fullName>
            </value>
            <value>
                <fullName>On Appeal</fullName>
            </value>
            <value>
                <fullName>Stayed</fullName>
            </value>
            <value>
                <fullName>Landmark</fullName>
            </value>
            <value>
                <fullName>Pending Federal Court Review</fullName>
            </value>
            <value>
                <fullName>Reviewed by Federal Court</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Statute__c.field-meta.xml
<CustomField>
    <fullName>Statute__c</fullName>
    <label>Statute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clean Air Act</fullName>
            </value>
            <value>
                <fullName>Clean Water Act</fullName>
            </value>
            <value>
                <fullName>Comprehensive Environmental Response Compensation and Liability Act</fullName>
            </value>
            <value>
                <fullName>Emergency Planning and Community Right-to-Know Act</fullName>
            </value>
            <value>
                <fullName>Equal Access to Justice</fullName>
            </value>
            <value>
                <fullName>Equal Employment Opportunity</fullName>
            </value>
            <value>
                <fullName>Federal Insecticide Act</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sample1</fullName>
            </value>
            <value>
                <fullName>CAFO</fullName>
            </value>
            <value>
                <fullName>CAFO w/Compliance Order</fullName>
            </value>
            <value>
                <fullName>CAFO w/SEP</fullName>
            </value>
            <value>
                <fullName>CAFO w/Injunctive Relief</fullName>
            </value>
            <value>
                <fullName>no penalty</fullName>
            </value>
            <value>
                <fullName>ESA</fullName>
            </value>
            <value>
                <fullName>ESA w/ Compliance</fullName>
            </value>
            <value>
                <fullName>On Consent (AOC) Plan</fullName>
            </value>
            <value>
                <fullName>Unilateral (UAO)</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Penalty only (w/proposed amount)</fullName>
            </value>
            <value>
                <fullName>Penalty only (notice pleading)</fullName>
            </value>
            <value>
                <fullName>Penalty (proposed amount) w/ Compliance Order</fullName>
            </value>
            <value>
                <fullName>Penalty (notice pleading) w/ Compliance Order</fullName>
            </value>
            <value>
                <fullName>CAA (not 112(r))</fullName>
            </value>
            <value>
                <fullName>CAA 112(r)</fullName>
            </value>
            <value>
                <fullName>CWA</fullName>
            </value>
            <value>
                <fullName>CERCLA</fullName>
            </value>
            <value>
                <fullName>RCRA</fullName>
            </value>
            <value>
                <fullName>SDWA</fullName>
            </value>
            <value>
                <fullName>TSCA 207</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>40 C.F.R. 1.25(e)</fullName>
            </value>
            <value>
                <fullName>Administrative Order</fullName>
            </value>
            <value>
                <fullName>ADR</fullName>
            </value>
            <value>
                <fullName>CAFO (using 22.13(b) to simultaneously commence and conclude)</fullName>
            </value>
            <value>
                <fullName>CERCLA 106(b)</fullName>
            </value>
            <value>
                <fullName>CERCLA 107(r) Agreement</fullName>
            </value>
            <value>
                <fullName>CERCLA 122(h) Cost Recovery Settlement</fullName>
            </value>
            <value>
                <fullName>CERCLA Lien – 107(l)</fullName>
            </value>
            <value>
                <fullName>CERCLA Prospective Purchaser Agreement</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>EAJA</fullName>
            </value>
            <value>
                <fullName>EEO</fullName>
            </value>
            <value>
                <fullName>Enforcement Appeals</fullName>
            </value>
            <value>
                <fullName>Federal Facility Compliance Agreement</fullName>
            </value>
            <value>
                <fullName>Field Citation (RCRA – RUST/LUST)</fullName>
            </value>
            <value>
                <fullName>Improper Practice</fullName>
            </value>
            <value>
                <fullName>Judicial Stipulated Penalty</fullName>
            </value>
            <value>
                <fullName>Notice of Determination (NOD)</fullName>
            </value>
            <value>
                <fullName>Notice of Noncompliance (NON)</fullName>
            </value>
            <value>
                <fullName>Notice of Refusal of Admission (FIFRA)</fullName>
            </value>
            <value>
                <fullName>Notice of Violation (NOV)</fullName>
            </value>
            <value>
                <fullName>Other (Type)</fullName>
            </value>
            <value>
                <fullName>Permit Appeals</fullName>
            </value>
            <value>
                <fullName>Quick Resolution</fullName>
            </value>
            <value>
                <fullName>Specially delegated by Administrator</fullName>
            </value>
            <value>
                <fullName>Stop Sale, Use or Removal Order (SSURO) - FIFRA</fullName>
            </value>
            <value>
                <fullName>Sua Sponte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MatterController.cls
public with sharing class MatterController {

    static Integer PAGE_SIZE = 9;

    public class Filters {
        @AuraEnabled
        public String searchKey { get; set; }
        @AuraEnabled
        public String[] types { get; set; }
        @AuraEnabled
        public String[] subtypes { get; set; }
        @AuraEnabled
        public String[] statutes { get; set; }
        @AuraEnabled
        public Date beginningDecisionDate{ get; set; }
        @AuraEnabled
        public Date endingDecisionDate{ get; set; }
        
    }

    @AuraEnabled(Cacheable=true)
    public static PagedResult getMatters(Filters filters, Integer pageNumber) {
        String key, whereClause = '';
        Date beginningDate;
        Date endingDate;
        String[] types, subtypes, statutes, stage, status, criteria = new List<String>{};
        if (filters != null) {
            beginningDate = filters.beginningDecisionDate;
            endingDate = filters.endingDecisionDate;
            types = filters.types;
            subtypes = filters.subtypes;
            statutes = filters.statutes;

            System.debug('Beginning Date: ' + beginningDate);
            System.debug('Ending Date: ' + endingDate);
            System.debug('Type: ' + types);
            System.debug('Subtype: ' + subtypes);
            System.debug('Statute: ' + statutes);
            
            if ( !String.isEmpty( filters.searchKey )) {
                key = '%' + filters.searchKey + '%';
                criteria.add('Name LIKE :key');
            }
            if ( filters.beginningDecisionDate != null ) {
                beginningDate = filters.beginningDecisionDate;
                criteria.add('Decision_Date__c >= :beginningDate');
            }
            if ( filters.endingDecisionDate != null ) {
                beginningDate = filters.endingDecisionDate;
                criteria.add('Decision_Date__c <= :endingDate');
            }
            if (filters.types != null) {
                types = filters.types;
                criteria.add('Type__c IN :types');
            }
            if (filters.subtypes != null) {
                subtypes = filters.subtypes;
                criteria.add('Subtype__c IN :subtypes');
            }
            if (filters.statutes != null) {
                statutes = filters.statutes;
                criteria.add('Statute__c IN :statutes');
            }
            if (criteria.size() > 0) {
                whereClause = 'WHERE ' + String.join(criteria, ' AND ');
            }
        }
        Integer pageSize = MatterController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PagedResult result = new PagedResult();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;

        System.debug( 'SELECT Id, Name, Matter_Number__c, Stage__c, Status__c, Statute__c, Type__c, Subtype__c FROM Matter__c ' +
        whereClause +
        ' WITH SECURITY_ENFORCED' +
        ' ORDER BY Name LIMIT :pageSize OFFSET :offset');
        
        result.totalItemCount = Database.countQuery(
            'SELECT count() FROM Matter__c ' + whereClause
        );
        result.records = Database.query(
            'SELECT Id, Name, Matter_Number__c, Stage__c, Status__c, Statute__c, Type__c, Subtype__c FROM Matter__c ' +
            whereClause +
            ' WITH SECURITY_ENFORCED' +
            ' ORDER BY Name LIMIT :pageSize OFFSET :offset'
        );
        return result;
    }
}